#!/usr/bin/env bash

set -e

git checkout -b deploy

function cleanup_at_exit {
  git checkout master
  git branch -D deploy
}
trap cleanup_at_exit EXIT

yarn build

git add -f public/index.html public/bundle.js public/bundle.js.map

git commit --allow-empty -m 'Deploying'

git push --force heroku deploy:master
